config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  namespace :api do
    post 'sign_in_token', to: 'api_application#sign_in'
    get 'users/me', to: 'users#me'
    get 'alerts', to: 'alerts#alerts'
    resources :stocks, only: [:index] do
      get 'search', on: :collection
    end
  end

  root to: 'static_pages#welcome'

  get 'auth/facebook/callback', to: 'users#facebook'

  # For the swagger json api definition generation
  resources :apidocs, only: [:index]
  
  get 'welcome', to: 'static_pages#welcome'
  get 'about', to: 'static_pages#about'
  get 'apidocs', to: 'apidocs#index'
  

  resources :stocks do
    get 'search', on: :collection
    get 'elastic', on: :collection
  end
  resources :alerts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
  end
  
  def about
  end
  
  def elastic
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.haml
%h1 About Stocks
.well
  %h3 Summary
  = I18n.t 'about.summary'
.well
  %h3 Technological Stack
  %ul
    %li= I18n.t 'about.technology1'
    %li= I18n.t 'about.technology2'
    %li= I18n.t 'about.technology3'
  %p=raw "StackShare : #{link_to 'Marhic Jerome Stack', 'https://stackshare.io/MarhicJeromeGIT/web-development-stack'}"
.well
  %h3 Future developments
  = I18n.t 'about.future'

app/views/static_pages/welcome.haml
.jumbotron
  %h1= I18n.t 'static_pages.welcome.title'
  %p
    = I18n.t 'static_pages.welcome.presentation'
  %p
    =link_to "View stocks", stocks_path, {class: "btn btn-lg btn-default"}