config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  namespace :api do
    post 'sign_in_token', to: 'api_application#sign_in'
    get 'users/me', to: 'users#me'
    get 'alerts', to: 'alerts#alerts'
    resources :stocks, only: [:index] do
      get 'search', on: :collection
    end
  end

  root to: 'static_pages#welcome'

  get 'auth/facebook/callback', to: 'users#facebook'

  # For the swagger json api definition generation
  resources :apidocs, only: [:index]
  
  get 'welcome', to: 'static_pages#welcome'
  get 'about', to: 'static_pages#about'
  get 'apidocs', to: 'apidocs#index'
  

  resources :stocks do
    get 'search', on: :collection
    get 'elastic', on: :collection
  end
  resources :alerts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/stock.rb
require 'elasticsearch/model'

class Stock < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  has_one :stock_live_info, autosave: true, dependent: :destroy
  
  after_initialize do |stock|
    create_stock_live_info if stock.new_record?
  end
  
  validates :name, presence: true
  validates :code, presence: true
  validates :stock_live_info, presence: true

  # helper to get the current value of the stock
  def value
    return self.stock_live_info.value_now
  end
  
  private
    def create_stock_live_info
      self.build_stock_live_info
    end
end

app/controllers/api/stocks_controller.rb
module Api
  class StocksController < ActionController::Base
    include Swagger::Blocks
    
    protect_from_forgery with: :null_session
    skip_before_action :verify_authenticity_token
    respond_to :json

    swagger_path '/stocks' do
      operation :get do
        key :description, 'Returns the list of the stocks'
        key :operationId, 'stocks'
        key :tags, [
          'stock'
        ]
        response 200 do
          key :description, 'stock response'
          schema do
            key :'$ref', :Stock
          end
        end
        response :default do
          key :description, 'unexpected error'
          schema do
            key :'$ref', :ErrorModel
          end
        end
      end
    end
  
    def index
      render json: Stock.all
    end
    
    def search
      query = ActiveRecord::Base::sanitize params[:search]
      response = Stock.search query
      @stocks = response.records
      
      render json: @stocks
    end
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :update, :destroy]

  before_action :authenticate_user!, except: [:index, :show]

  after_action :verify_authorized, except: [:index, :search, :elastic]
  after_action :verify_policy_scoped, only: :index

  # GET /stocks
  def index
    @stocks = policy_scope(Stock)
    
    respond_to do |format|
      format.html
      format.json { render json: @stocks}
    end
  end

  # GET /stocks/1
  def show
    respond_to do |format|
      format.html
      format.json { render json: @stock}
    end
  end

  # POST /stocks
  def create
    @stock = Stock.new(stock_params)

    if @stock.save
      render json: @stock, status: :created, location: @stock
    else
      render json: @stock.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /stocks/1
  def update
    if @stock.update(stock_params)
      render json: @stock
    else
      render json: @stock.errors, status: :unprocessable_entity
    end
  end

  # DELETE /stocks/1
  def destroy
    @stock.destroy
  end

  def elastic
  end

  def search
    query = ActiveRecord::Base::sanitize params[:search]
    response = Stock.search query
    @stocks = response.records
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
      authorize @stock
    end

    # Only allow a trusted parameter "white list" through.
    def stock_params
      params.require(:stock).permit(:code, :codif, :name, :place)
    end
end

app/views/stocks/_stock.haml
%li.stock_search
  =link_to '#' do 
    %h2= stock.name

app/views/stocks/elastic.haml
%p
  Elastic search server status:
  %b
    = Stock.__elasticsearch__.client.cluster.health['status']

= form_tag search_stocks_path, method: :get, remote: true do
  = text_field_tag :search
  = submit_tag 'Search'
#results
  %p.search_results
  %ul.list

app/views/stocks/index.haml
.well
  %p
    = I18n.t 'stocks.pick_up'
  %table#stocks_table.table.table-striped.table-bordered.dataTable.no-footer
    %thead
      %th Stock
    %tbody
      -@stocks.each do |s|
        %tr
          %td
            =link_to s do
              %strong
                = s.name
              = "(#{s.code})"

app/views/stocks/search.js.erb
console.log("rendering <%= @stocks.count %> results");
$('#results ul.list').empty(); // Erase previous results.
$('#results p.search_results').html("<%= pluralize(@stocks.count, 'result') %> found");
<% @stocks.each do |stock| %>
  <%  %>
  $('#results ul.list').append("<%= escape_javascript render stock %>");
<% end %>

app/views/stocks/show.haml
.col.col-md-12
  %div.panel.panel-primary
    %div.panel-heading.text-center
      =@stock.name
    %div.panel-body
      %fieldset
        %legend
          Valeur en temps réel
        = react_component("Stock", { value_now: @stock.stock_live_info.value_now, |
                                     value_open: @stock.stock_live_info.value_open, |
                                     value_low: @stock.stock_live_info.value_low, |
                                     value_high: @stock.stock_live_info.value_high })
      =render partial: 'alerts/new_alert', locals: { alert: Alert.new(stock: @stock) }